### ISSUE TITLE
윈도우 크기를 줄이면 간혹 오른쪽에 이상한 셀이 생깁니다.

### ISSUE THREAD

**Issue by kbs0327** [nhnent/tui.grid#4]
![image](https://cloud.githubusercontent.com/assets/8895856/12776643/1843fade-ca9b-11e5-9345-545cccf56ce7.png)

재현 순서
1. grid를 작성합니다.
2. window를 줄여서 grid의 최소 크기보다 더 줄입니다.
3. 간혹 스크롤 오른쪽에 dummy cell이 생깁니다.

**Comment by dongwoo-kim** [comment]
실제 확인해 보니 해당 페이지에 다음과 같은 css 룰이 그리드와 충돌하는 것 같습니다.
```css
#main-wrapper,#main-wrapper .header {
    min-width: 600px;
}
```
조만간 그리드에서 모든 클래스명에 prefix 를 추가할 계획입니다만..  그 전까지는
```css
#main-wrapper .uio_grid .header {
    min-width: 0
}
```
와 같은 식으로 방어코드를 추가해서 사용하시면 될 것 같습니다.
