### ISSUE TITLE
summary 부분에 좌측정렬은 어떻게 해야하나요?

### ISSUE THREAD

**Issue by ryujb** [nhnent/tui.grid#93]
summary 부분에
columnContent:{
ORDER_DT: {
template: function(valueMap) {
          return "total";
          }
        },
ORDER_CNT: {
          template: function(valueMap) {
                    return valueMap.sum.toString().replace(/\B(?=(\d{3})+\b)/g, ",");
                    }
          }
}
이런식으로 설정을 하면 가운데 정렬이 되는데 이것을 좌측정렬을 할려면 어떻게해야하나요?

**Comment by seonim-ryu** [comment]
@ryujb 
css 스타일을 오버라이드하여 처리할 수 있습니다.
아래 셀렉터에 원하는 스타일을 추가하여 사용바랍니다.

```css
.tui-grid-summary-area .tui-grid-cell {
    text-align: left;
}
```

그리고 이후 이슈 등록 시에는 꼭 `이슈 템플릿` 양식에 맞게 작성 부탁드립니다.
감사합니다. :)
